import { NextRequest, NextResponse } from "next/server";
import { runAudit } from "@/lib/audit";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
// Allow time for live web research when the LLM engine is enabled.
export const maxDuration = 60;

// GET /api/audit?url=example.com
//
// If OPENROUTER_API_KEY is set, the report is generated by Claude (via
// OpenRouter, with optional web search). Otherwise a heuristic engine that
// reads real on-page signals is used. See lib/audit.ts and lib/llm.ts.
export async function GET(req: NextRequest) {
  const url = req.nextUrl.searchParams.get("url");

  if (!url || url.trim().length < 3) {
    return NextResponse.json(
      { error: "Provide a ?url= parameter, e.g. /api/audit?url=example.com" },
      { status: 400 },
    );
  }

  try {
    const report = await runAudit(url);
    return NextResponse.json(report);
  } catch (err) {
    console.error("Audit failed:", err);
    return NextResponse.json(
      { error: "We couldn't complete the audit for that URL. Check the address and try again." },
      { status: 502 },
    );
  }
}
