import { NextRequest, NextResponse } from "next/server";
import { runAudit } from "@/lib/audit";
import { logAudit } from "@/lib/supabase";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
// Allow time for live web research when the LLM engine is enabled.
export const maxDuration = 60;

// GET /api/audit?url=example.com
//
// If OPENROUTER_API_KEY is set, the report is generated by Claude (via
// OpenRouter, with optional web search). Otherwise a heuristic engine that
// reads real on-page signals is used. See lib/audit.ts and lib/llm.ts.
// Each audit is logged to Supabase when configured (see lib/supabase.ts).
export async function GET(req: NextRequest) {
  const url = req.nextUrl.searchParams.get("url");

  if (!url || url.trim().length < 3) {
    return NextResponse.json(
      { error: "Provide a ?url= parameter, e.g. /api/audit?url=example.com" },
      { status: 400 },
    );
  }

  try {
    const { report, engine, webSearch } = await runAudit(url);

    // Lowest two dimensions, for spotting patterns across properties.
    const worst = [...report.breakdown]
      .sort((a, b) => a.score - b.score)
      .slice(0, 2)
      .map((b) => ({ label: b.label, score: b.score }));

    await logAudit({
      url: report.url,
      domain: report.domain,
      property_name: report.propertyName,
      score: report.overallScore,
      grade: report.grade,
      engine,
      web_search: webSearch,
      appears: report.aiVisibility.appears,
      worst_dimensions: worst,
    });

    return NextResponse.json(report);
  } catch (err) {
    console.error("Audit failed:", err);
    return NextResponse.json(
      { error: "We couldn't complete the audit for that URL. Check the address and try again." },
      { status: 502 },
    );
  }
}
